version: 2

jobs:
  build:
    steps:
      # ... steps for building/testing app ...
      - setup_remote_docker

      - run:
         docker-compose -f docker-compose.yml -p testingdocker  build
         docker-compose -f docker-compose.yml -p testingdocker  up -d